<p>I use </b>no-ip.com</b> for <b>DNS</b> routing because I have a dynamic IP from my cable provider.  On the client side, I use <b>ddclient</b> to update 
the ip on <b>no-ip.com</b> whenever I'm assigned one from the ISP.  I've been having a little difficulty with this, and am currently using this 
configuration.</p>
<code>
# Configuration file for ddclient generated by debconf<br />
#<br />
# /etc/ddclient.conf<br />
<br />
protocol=noip<br />
use=web<br />
server=www.no-ip.com<br />
login=youremail@wherever.com<br />
password='(actually type your password in between the single quotes, no parathenses)'<br />
beaver-pi.myvnc.com<br />
</code>
<p>I have a Netgear wireless router that the <b>Pi</b> is wired into.  Using the router's internal configuration, I assigned a static IP to the
<b>Pi</b> so that I can also use port forwarding to open up my ports for remote access.</p>

<p>I have not editted any <b>Linux</b> configuration files to establish a local static <b>IP</b>.  I do not believe that this is necessary since the router identifies
the <b>MAC</b> address on my <b>Pi</b> and assigns it's own static <b>IP</b>.  I have noticed other router firmware that will not allow local static 
<b>IP</b> assignments, and this may be when it is necessary in the <b>Pi</b> configuration.</p>